services:
  wordpress:
    build: .docker
    image: wordpress-local
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mysql
    volumes:
      - wordpress:/var/www/html
      - ./plugins/:/var/www/html/wp-content/plugins

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,cached
    depends_on:
      - wordpress

volumes:
  wordpress:
  db-data: