FROM wordpress:6.0.2-php8.0-fpm-alpine
LABEL maintainer="salvatorebalzano@hotmail.it"

# Installing composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer